name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  lint:
    name: Lint Code
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_INTERACTION: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --optimize-autoloader

      - name: Run Lint
        run: composer lint

      - name: Reset composer files
        if: always()
        run: |
          git checkout HEAD -- composer.json composer.lock 2>/dev/null || true

      - name: Commit lint fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        if: github.event_name == 'push'
        with:
          commit_message: 'style: apply automated lint fixes'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          file_pattern: '*.php'
